- Target: nmaguiar/netutils:build (alpine 3.20.2)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-43790
    PkgID: vim@9.1.0678-r0
    PkgName: vim
    PkgIdentifier:
      PURL: pkg:apk/alpine/vim@9.1.0678-r0?arch=x86_64&distro=3.20.2
      UID: 7d6aacfbc7c2d514
    InstalledVersion: 9.1.0678-r0
    FixedVersion: 9.1.0707-r0
    Status: fixed
    Layer:
      Digest: sha256:392d1a12caab2c676c7eb1101602d51136ce2eb3c797bf1eb41bc16bc571c5db
      DiffID: sha256:2a920f2cc7f2e7946faee2fe54222c7acf15f676d37776e2121f4778733f7e52
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-43790
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'vim: Out of bounds read when performing a search command'
    Description: Vim is an open source command line text editor. When performing a search and displaying the search-count message is disabled (:set shm+=S), the search pattern is displayed at the bottom of the screen in a buffer (msgbuf). When right-left mode (:set rl) is enabled, the search pattern is reversed. This happens by allocating a new buffer. If the search pattern contains some ASCII NUL characters, the buffer allocated will be smaller than the original allocated buffer (because for allocating the reversed buffer, the strlen() function is called, which only counts until it notices an ASCII NUL byte ) and thus the original length indicator is wrong. This causes an overflow when accessing characters inside the msgbuf by the previously (now wrong) length of the msgbuf. The issue has been fixed as of Vim patch v9.1.0689.
    Severity: MEDIUM
    CweIDs:
    - CWE-122
    VendorSeverity:
      redhat: 2
    References:
    - https://access.redhat.com/security/cve/CVE-2024-43790
    - https://github.com/vim/vim/commit/cacb6693c10bb19f28a50eca47bc
    - https://github.com/vim/vim/security/advisories/GHSA-v2x2-cjcg-f9jm
    - https://nvd.nist.gov/vuln/detail/CVE-2024-43790
    - https://www.cve.org/CVERecord?id=CVE-2024-43790
    PublishedDate: '2024-08-22T22:15:05.317Z'
    LastModifiedDate: '2024-08-23T16:18:28.547Z'
  - VulnerabilityID: CVE-2024-43802
    PkgID: vim@9.1.0678-r0
    PkgName: vim
    PkgIdentifier:
      PURL: pkg:apk/alpine/vim@9.1.0678-r0?arch=x86_64&distro=3.20.2
      UID: 7d6aacfbc7c2d514
    InstalledVersion: 9.1.0678-r0
    FixedVersion: 9.1.0707-r0
    Status: fixed
    Layer:
      Digest: sha256:392d1a12caab2c676c7eb1101602d51136ce2eb3c797bf1eb41bc16bc571c5db
      DiffID: sha256:2a920f2cc7f2e7946faee2fe54222c7acf15f676d37776e2121f4778733f7e52
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-43802
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'vim: Heap Buffer Overflow in Vim''s Typeahead Buffer Handling'
    Description: Vim is an improved version of the unix vi text editor. When flushing the typeahead buffer, Vim moves the current position in the typeahead buffer but does not check whether there is enough space left in the buffer to handle the next characters.  So this may lead to the tb_off position within the typebuf variable to point outside of the valid buffer size, which can then later lead to a heap-buffer overflow in e.g. ins_typebuf(). Therefore, when flushing the typeahead buffer, check if there is enough space left before advancing the off position. If not, fall back to flush current typebuf contents. It's not quite clear yet, what can lead to this situation. It seems to happen when error messages occur (which will cause Vim to flush the typeahead buffer) in comnination with several long mappgins and so it may eventually move the off position out of a valid buffer size. Impact is low since it is not easily reproducible and requires to have several mappings active and run into some error condition. But when this happens, this will cause a crash. The issue has been fixed as of Vim patch v9.1.0697. Users are advised to upgrade. There are no known workarounds for this issue.
    Severity: MEDIUM
    CweIDs:
    - CWE-122
    VendorSeverity:
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:U/C:L/I:L/A:L
        V3Score: 4.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-43802
    - https://github.com/vim/vim/commit/322ba9108612bead5eb
    - https://github.com/vim/vim/security/advisories/GHSA-4ghr-c62x-cqfh
    - https://nvd.nist.gov/vuln/detail/CVE-2024-43802
    - https://www.cve.org/CVERecord?id=CVE-2024-43802
    PublishedDate: '2024-08-26T19:15:07.943Z'
    LastModifiedDate: '2024-08-27T13:02:05.683Z'
  - VulnerabilityID: CVE-2024-43790
    PkgID: vim-common@9.1.0678-r0
    PkgName: vim-common
    PkgIdentifier:
      PURL: pkg:apk/alpine/vim-common@9.1.0678-r0?arch=x86_64&distro=3.20.2
      UID: 862970c617dbc19
    InstalledVersion: 9.1.0678-r0
    FixedVersion: 9.1.0707-r0
    Status: fixed
    Layer:
      Digest: sha256:392d1a12caab2c676c7eb1101602d51136ce2eb3c797bf1eb41bc16bc571c5db
      DiffID: sha256:2a920f2cc7f2e7946faee2fe54222c7acf15f676d37776e2121f4778733f7e52
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-43790
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'vim: Out of bounds read when performing a search command'
    Description: Vim is an open source command line text editor. When performing a search and displaying the search-count message is disabled (:set shm+=S), the search pattern is displayed at the bottom of the screen in a buffer (msgbuf). When right-left mode (:set rl) is enabled, the search pattern is reversed. This happens by allocating a new buffer. If the search pattern contains some ASCII NUL characters, the buffer allocated will be smaller than the original allocated buffer (because for allocating the reversed buffer, the strlen() function is called, which only counts until it notices an ASCII NUL byte ) and thus the original length indicator is wrong. This causes an overflow when accessing characters inside the msgbuf by the previously (now wrong) length of the msgbuf. The issue has been fixed as of Vim patch v9.1.0689.
    Severity: MEDIUM
    CweIDs:
    - CWE-122
    VendorSeverity:
      redhat: 2
    References:
    - https://access.redhat.com/security/cve/CVE-2024-43790
    - https://github.com/vim/vim/commit/cacb6693c10bb19f28a50eca47bc
    - https://github.com/vim/vim/security/advisories/GHSA-v2x2-cjcg-f9jm
    - https://nvd.nist.gov/vuln/detail/CVE-2024-43790
    - https://www.cve.org/CVERecord?id=CVE-2024-43790
    PublishedDate: '2024-08-22T22:15:05.317Z'
    LastModifiedDate: '2024-08-23T16:18:28.547Z'
  - VulnerabilityID: CVE-2024-43802
    PkgID: vim-common@9.1.0678-r0
    PkgName: vim-common
    PkgIdentifier:
      PURL: pkg:apk/alpine/vim-common@9.1.0678-r0?arch=x86_64&distro=3.20.2
      UID: 862970c617dbc19
    InstalledVersion: 9.1.0678-r0
    FixedVersion: 9.1.0707-r0
    Status: fixed
    Layer:
      Digest: sha256:392d1a12caab2c676c7eb1101602d51136ce2eb3c797bf1eb41bc16bc571c5db
      DiffID: sha256:2a920f2cc7f2e7946faee2fe54222c7acf15f676d37776e2121f4778733f7e52
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-43802
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'vim: Heap Buffer Overflow in Vim''s Typeahead Buffer Handling'
    Description: Vim is an improved version of the unix vi text editor. When flushing the typeahead buffer, Vim moves the current position in the typeahead buffer but does not check whether there is enough space left in the buffer to handle the next characters.  So this may lead to the tb_off position within the typebuf variable to point outside of the valid buffer size, which can then later lead to a heap-buffer overflow in e.g. ins_typebuf(). Therefore, when flushing the typeahead buffer, check if there is enough space left before advancing the off position. If not, fall back to flush current typebuf contents. It's not quite clear yet, what can lead to this situation. It seems to happen when error messages occur (which will cause Vim to flush the typeahead buffer) in comnination with several long mappgins and so it may eventually move the off position out of a valid buffer size. Impact is low since it is not easily reproducible and requires to have several mappings active and run into some error condition. But when this happens, this will cause a crash. The issue has been fixed as of Vim patch v9.1.0697. Users are advised to upgrade. There are no known workarounds for this issue.
    Severity: MEDIUM
    CweIDs:
    - CWE-122
    VendorSeverity:
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:U/C:L/I:L/A:L
        V3Score: 4.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-43802
    - https://github.com/vim/vim/commit/322ba9108612bead5eb
    - https://github.com/vim/vim/security/advisories/GHSA-4ghr-c62x-cqfh
    - https://nvd.nist.gov/vuln/detail/CVE-2024-43802
    - https://www.cve.org/CVERecord?id=CVE-2024-43802
    PublishedDate: '2024-08-26T19:15:07.943Z'
    LastModifiedDate: '2024-08-27T13:02:05.683Z'
  - VulnerabilityID: CVE-2024-43790
    PkgID: xxd@9.1.0678-r0
    PkgName: xxd
    PkgIdentifier:
      PURL: pkg:apk/alpine/xxd@9.1.0678-r0?arch=x86_64&distro=3.20.2
      UID: a9c1d0ab5afd58ea
    InstalledVersion: 9.1.0678-r0
    FixedVersion: 9.1.0707-r0
    Status: fixed
    Layer:
      Digest: sha256:392d1a12caab2c676c7eb1101602d51136ce2eb3c797bf1eb41bc16bc571c5db
      DiffID: sha256:2a920f2cc7f2e7946faee2fe54222c7acf15f676d37776e2121f4778733f7e52
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-43790
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'vim: Out of bounds read when performing a search command'
    Description: Vim is an open source command line text editor. When performing a search and displaying the search-count message is disabled (:set shm+=S), the search pattern is displayed at the bottom of the screen in a buffer (msgbuf). When right-left mode (:set rl) is enabled, the search pattern is reversed. This happens by allocating a new buffer. If the search pattern contains some ASCII NUL characters, the buffer allocated will be smaller than the original allocated buffer (because for allocating the reversed buffer, the strlen() function is called, which only counts until it notices an ASCII NUL byte ) and thus the original length indicator is wrong. This causes an overflow when accessing characters inside the msgbuf by the previously (now wrong) length of the msgbuf. The issue has been fixed as of Vim patch v9.1.0689.
    Severity: MEDIUM
    CweIDs:
    - CWE-122
    VendorSeverity:
      redhat: 2
    References:
    - https://access.redhat.com/security/cve/CVE-2024-43790
    - https://github.com/vim/vim/commit/cacb6693c10bb19f28a50eca47bc
    - https://github.com/vim/vim/security/advisories/GHSA-v2x2-cjcg-f9jm
    - https://nvd.nist.gov/vuln/detail/CVE-2024-43790
    - https://www.cve.org/CVERecord?id=CVE-2024-43790
    PublishedDate: '2024-08-22T22:15:05.317Z'
    LastModifiedDate: '2024-08-23T16:18:28.547Z'
  - VulnerabilityID: CVE-2024-43802
    PkgID: xxd@9.1.0678-r0
    PkgName: xxd
    PkgIdentifier:
      PURL: pkg:apk/alpine/xxd@9.1.0678-r0?arch=x86_64&distro=3.20.2
      UID: a9c1d0ab5afd58ea
    InstalledVersion: 9.1.0678-r0
    FixedVersion: 9.1.0707-r0
    Status: fixed
    Layer:
      Digest: sha256:392d1a12caab2c676c7eb1101602d51136ce2eb3c797bf1eb41bc16bc571c5db
      DiffID: sha256:2a920f2cc7f2e7946faee2fe54222c7acf15f676d37776e2121f4778733f7e52
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-43802
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'vim: Heap Buffer Overflow in Vim''s Typeahead Buffer Handling'
    Description: Vim is an improved version of the unix vi text editor. When flushing the typeahead buffer, Vim moves the current position in the typeahead buffer but does not check whether there is enough space left in the buffer to handle the next characters.  So this may lead to the tb_off position within the typebuf variable to point outside of the valid buffer size, which can then later lead to a heap-buffer overflow in e.g. ins_typebuf(). Therefore, when flushing the typeahead buffer, check if there is enough space left before advancing the off position. If not, fall back to flush current typebuf contents. It's not quite clear yet, what can lead to this situation. It seems to happen when error messages occur (which will cause Vim to flush the typeahead buffer) in comnination with several long mappgins and so it may eventually move the off position out of a valid buffer size. Impact is low since it is not easily reproducible and requires to have several mappings active and run into some error condition. But when this happens, this will cause a crash. The issue has been fixed as of Vim patch v9.1.0697. Users are advised to upgrade. There are no known workarounds for this issue.
    Severity: MEDIUM
    CweIDs:
    - CWE-122
    VendorSeverity:
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:U/C:L/I:L/A:L
        V3Score: 4.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-43802
    - https://github.com/vim/vim/commit/322ba9108612bead5eb
    - https://github.com/vim/vim/security/advisories/GHSA-4ghr-c62x-cqfh
    - https://nvd.nist.gov/vuln/detail/CVE-2024-43802
    - https://www.cve.org/CVERecord?id=CVE-2024-43802
    PublishedDate: '2024-08-26T19:15:07.943Z'
    LastModifiedDate: '2024-08-27T13:02:05.683Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
- Target: Python
  Class: lang-pkgs
  Type: python-pkg
