name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '43 0 * * 6'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get artifact mitmproxy-x64
      uses: actions/download-artifact@v2
      with:
        name: mitmproxy_x64

    - name: Get artifact mitmproxy-arm64
      uses: actions/download-artifact@v2
      with:
        name: mitmproxy_arm64

    - name: Select an artifact based on architecture
      run: |
        if [ "$(uname -m)" = "x86_64" ]; then
          mv -r mitmproxy-x64/* mitmproxy
        else
          mv -r mitmproxy-arm64/* mitmproxy
        fi

    - uses: docker/build-push-action@v3
      name: Build and push
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: nmaguiar/netutils:build