name: Scan Versions

on:
  workflow_dispatch:
  schedule:
  - cron: '07 7 * * *'

jobs:
  Scan-Images:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name       : Scan version
    steps      :
    - uses: actions/checkout@v4
      name: Checkoout

    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-nightly
        path: /tmp/oaf

    - name: Get versions
      run : |
        docker --rm -ti nmaguiar/netutils:build /openaf/ojob /openaf/ojobs/softVersions.yaml -json > .github/softVersions-build.json

    - uses: openaf/ojob-action@v4
      name: Check latest
      with:
        ojob: 'ojob.io/sec/genSecBadge'
        args: 'image=nmaguiar/netutils:latest file=.github/sec-latest.svg reportFile=.github/sec-latest.yaml'
        dist: 'nightly'

    - uses: openaf/ojob-action@v4
      name: Update files
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: 'ojob.io/git/hub/contentIn'
        args: 'message="update\ versions\ {{date}}/{{time}}" title="Update\ versions" paths=.github/'
        dist: 'nightly'